services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,dynamodb,s3
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - service_network

  {{cookiecutter.project_slug}}:
    container_name: {{cookiecutter.project_slug}}
    depends_on:
      - localstack
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.local
    ports:
      - "8000:8000"
    env_file: 
      - ../.env
    networks:
      - service_network
    
networks:
  service_network:
    name: service_network
    driver: bridge
